global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'uber-eats-clone-register'
    metrics_path: '/q/metrics'
    scrape_interval:     5s
    static_configs:
      - targets: ['host.docker.internal:8080']
